version: '3.9'
services:
  dev-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nhahothanh2564.
      POSTGRES_DB: localhost
    ports:
      - '5434:5432'
    networks:
      - nhahothanh
  test-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nhahothanh2564.
      POSTGRES_DB: localhost
    ports:
      - '5435:5432'
    networks:
      - nhahothanh
networks:
  nhahothanh:
